name: Deploy Python Azure Functions
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.10' }
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: CVE-Sigma        # use the resource name
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
